// In-memory Shared Produce Pool store
export const sharedPools: any[] = [
  {
    id: "pool-001",
    poolNumber: "POOL-HR-KNL-01",
    hostFarmerName: "Baldev Singh",
    hostFarmerPhone: "9876543220",
    originVillage: "Taraori",
    district: "Karnal",
    destinationCentreName: "Karnal Central APMC Mandi",
    destinationCentreId: "cmt9zrhlu000t10oa3h68pb0c",
    scheduledDeparture: "Tomorrow, 08:30 AM",
    vehicleType: "TRACTOR_TROLLEY_XL",
    totalCapacityQuintals: 70.0,
    filledQuantityQuintals: 42.0,
    availableCapacityQuintals: 28.0,
    cropType: "WHEAT",
    estimatedCostPerQuintal: 45,
    savingsPercentage: 68,
    status: "OPEN",
    participants: [
      { farmerName: "Baldev Singh (Host)", quantity: 25.0, village: "Taraori" },
      { farmerName: "Kuldeep Yadav", quantity: 17.0, village: "Taraori" },
    ],
  },
  {
    id: "pool-002",
    poolNumber: "POOL-HR-NLK-02",
    hostFarmerName: "Suresh Patel",
    hostFarmerPhone: "9876543221",
    originVillage: "Gharaunda",
    district: "Karnal",
    destinationCentreName: "Nilokheri Cooperative PACS Centre",
    destinationCentreId: "cmt9zrhmz001210oaikakfecr",
    scheduledDeparture: "Today, 02:00 PM",
    vehicleType: "EICHER_CANTER_14FT",
    totalCapacityQuintals: 90.0,
    filledQuantityQuintals: 65.0,
    availableCapacityQuintals: 25.0,
    cropType: "WHEAT",
    estimatedCostPerQuintal: 55,
    savingsPercentage: 62,
    status: "OPEN",
    participants: [
      { farmerName: "Suresh Patel (Host)", quantity: 30.0, village: "Gharaunda" },
      { farmerName: "Manjeet Gill", quantity: 20.0, village: "Gharaunda" },
      { farmerName: "Ram Kishan", quantity: 15.0, village: "Gharaunda" },
    ],
  },
  {
    id: "pool-003",
    poolNumber: "POOL-PB-LDH-03",
    hostFarmerName: "Harpreet Kaur",
    hostFarmerPhone: "9876543222",
    originVillage: "Samrala",
    district: "Ludhiana",
    destinationCentreName: "Samrala Block PACS Depot",
    destinationCentreId: "cmt9zrhos001610oa00l5jshf",
    scheduledDeparture: "Tomorrow, 09:00 AM",
    vehicleType: "TRACTOR_TROLLEY",
    totalCapacityQuintals: 50.0,
    filledQuantityQuintals: 30.0,
    availableCapacityQuintals: 20.0,
    cropType: "PADDY",
    estimatedCostPerQuintal: 40,
    savingsPercentage: 71,
    status: "OPEN",
    participants: [
      { farmerName: "Harpreet Kaur (Host)", quantity: 20.0, village: "Samrala" },
      { farmerName: "Gurpreet Singh", quantity: 10.0, village: "Samrala" },
    ],
  },
];
